export const SampleConsumerData = [
  {
    name: "Raghvendra Raga",
    amount: "₹35,342",
    property1: "50.42g",
    property2: "50.42g",
    property3: "50.42g",
    totalAmount: "₹35,342",
    status: "Done",
    fieldExecutive: {
      role: "B2B Field Executive",
      name: "Arun Jha",
    },
    associate: {
      role: "Associate",
      name: "Anika Singh",
    },
    region: "South",
    businessType: "Business",
    contact: "9876543210@trucard",
  },
  {
    name: "John Doe",
    amount: "₹25,678",
    property1: "30.12g",
    property2: "40.20g",
    property3: "55.75g",
    totalAmount: "₹25,678",
    status: "Pending",
    fieldExecutive: {
      role: "Field Agent",
      name: "Sarah Smith",
    },
    associate: {
      role: "Assistant",
      name: "Michael Johnson",
    },
    region: "North",
    businessType: "Retail",
    contact: "1234567890@trucard",
  },
  {
    name: "Alice Williams",
    amount: "₹15,123",
    property1: "20.30g",
    property2: "15.50g",
    property3: "10.25g",
    totalAmount: "₹15,123",
    status: "In Progress",
    fieldExecutive: {
      role: "Sales Representative",
      name: "David Davis",
    },
    associate: {
      role: "Coordinator",
      name: "Emma Evans",
    },
    region: "West",
    businessType: "Wholesale",
    contact: "5678901234@trucard",
  },
  {
    name: "Sophie Brown",
    amount: "₹45,987",
    property1: "25.60g",
    property2: "35.75g",
    property3: "40.10g",
    totalAmount: "₹45,987",
    status: "Done",
    fieldExecutive: {
      role: "Account Manager",
      name: "Chris Wilson",
    },
    associate: {
      role: "Supervisor",
      name: "Olivia Miller",
    },
    region: "East",
    businessType: "Manufacturing",
    contact: "6789012345@trucard",
  },
  {
    name: "Ella Turner",
    amount: "₹18,765",
    property1: "15.80g",
    property2: "22.40g",
    property3: "30.50g",
    totalAmount: "₹18,765",
    status: "In Progress",
    fieldExecutive: {
      role: "Field Coordinator",
      name: "Daniel White",
    },
    associate: {
      role: "Assistant Manager",
      name: "Lily Johnson",
    },
    region: "Central",
    businessType: "Service",
    contact: "3456789012@trucard",
  },
  {
    name: "Noah Martinez",
    amount: "₹32,456",
    property1: "42.60g",
    property2: "38.25g",
    property3: "50.10g",
    totalAmount: "₹32,456",
    status: "Pending",
    fieldExecutive: {
      role: "Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Noah M",
    amount: "₹32,456",
    property1: "42.60g",
    property2: "38.25g",
    property3: "50.10g",
    totalAmount: "₹32,456",
    status: "Pending",
    fieldExecutive: {
      role: "Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Noah Martinez",
    amount: "₹32,456",
    property1: "42.60g",
    property2: "38.25g",
    property3: "50.10g",
    totalAmount: "₹32,456",
    status: "Pending",
    fieldExecutive: {
      role: "Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Noah Martinez",
    amount: "₹32,456",
    property1: "42.60g",
    property2: "38.25g",
    property3: "50.10g",
    totalAmount: "₹32,456",
    status: "Pending",
    fieldExecutive: {
      role: "Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Noah Martinez",
    amount: "₹32,456",
    property1: "42.60g",
    property2: "38.25g",
    property3: "50.10g",
    totalAmount: "₹32,456",
    status: "Pending",
    fieldExecutive: {
      role: "Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Rahul Sharma",
    amount: "₹40,000",
    property1: "60.20g",
    property2: "55.30g",
    property3: "45.50g",
    totalAmount: "₹40,000",
    status: "Done",
    fieldExecutive: {
      role: "Senior B2B Field Executive",
      name: "Arun Jha",
    },
    associate: {
      role: "Senior Associate",
      name: "Anika Singh",
    },
    region: "South",
    businessType: "Enterprise",
    contact: "9876543210@trucard",
  },
  {
    name: "James Smith",
    amount: "₹28,500",
    property1: "35.25g",
    property2: "45.75g",
    property3: "60.00g",
    totalAmount: "₹28,500",
    status: "Rejected",
    fieldExecutive: {
      role: "Senior Field Agent",
      name: "Sarah Smith",
    },
    associate: {
      role: "Senior Assistant",
      name: "Michael Johnson",
    },
    region: "North",
    businessType: "Retail",
    contact: "1234567890@trucard",
  },
  {
    name: "Lily Thompson",
    amount: "₹18,000",
    property1: "25.50g",
    property2: "20.20g",
    property3: "15.75g",
    totalAmount: "₹18,000",
    status: "In Progress",
    fieldExecutive: {
      role: "Senior Sales Representative",
      name: "David Davis",
    },
    associate: {
      role: "Senior Coordinator",
      name: "Emma Evans",
    },
    region: "West",
    businessType: "Wholesale",
    contact: "5678901234@trucard",
  },
  {
    name: "Sophia Brown",
    amount: "₹50,500",
    property1: "30.80g",
    property2: "40.75g",
    property3: "45.10g",
    totalAmount: "₹50,500",
    status: "Done",
    fieldExecutive: {
      role: "Senior Account Manager",
      name: "Chris Wilson",
    },
    associate: {
      role: "Senior Supervisor",
      name: "Olivia Miller",
    },
    region: "East",
    businessType: "Manufacturing",
    contact: "6789012345@trucard",
  },
  {
    name: "Ethan Turner",
    amount: "₹25,000",
    property1: "20.50g",
    property2: "28.40g",
    property3: "35.50g",
    totalAmount: "₹25,000",
    status: "In Progress",
    fieldExecutive: {
      role: "Senior Field Coordinator",
      name: "Daniel White",
    },
    associate: {
      role: "Senior Assistant Manager",
      name: "Lily Johnson",
    },
    region: "Central",
    businessType: "Service",
    contact: "3456789012@trucard",
  },
  {
    name: "Emma Martinez",
    amount: "₹36,000",
    property1: "50.60g",
    property2: "45.25g",
    property3: "60.10g",
    totalAmount: "₹36,000",
    status: "Pending",
    fieldExecutive: {
      role: "Senior Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Senior Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Oliver Davis",
    amount: "₹36,000",
    property1: "50.60g",
    property2: "45.25g",
    property3: "60.10g",
    totalAmount: "₹36,000",
    status: "Pending",
    fieldExecutive: {
      role: "Senior Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Senior Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Mia Clark",
    amount: "₹36,000",
    property1: "50.60g",
    property2: "45.25g",
    property3: "60.10g",
    totalAmount: "₹36,000",
    status: "Pending",
    fieldExecutive: {
      role: "Senior Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Senior Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
  {
    name: "Aiden Lee",
    amount: "₹36,000",
    property1: "50.60g",
    property2: "45.25g",
    property3: "60.10g",
    totalAmount: "₹36,000",
    status: "Pending",
    fieldExecutive: {
      role: "Senior Field Specialist",
      name: "Sophia Turner",
    },
    associate: {
      role: "Senior Team Lead",
      name: "William Brown",
    },
    region: "West",
    businessType: "Technology",
    contact: "8901234567@trucard",
  },
];
